name: 'Vault Pattern for NRM DAP'
description: 'Vault patterns intended for use within the NRM Data Analytics Platform (DAP)'
author: 'Data Foundations'
runs:
   using: 'docker'
   image: 'Dockerfile'
branding:
   icon: 'shield'
   color: 'blue'
